baseURL = "https://blog.itsalwaysthe.network/"
languageCode = "en-us"
title = "It's Always the Network"
theme = "fluency"

[markup]
  [markup.highlight]
    pygmentsUseClasses = true
    pygmentsCodefences = true

[menu]
[[menu.main]]
  identifier = "posts"
  name = "posts"
  url = "posts/"
  weight = 1
[[menu.main]]
  identifier = "tags"
  name = "tags"
  url = "tags/"
  weight = 5
[[menu.footer]]
  identifier = "twitter"
  url = "https://twitter.com/supertylerc"
  name = "Twitter"

[params]
mainSections = ["posts"]

